addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-scalafix" % "0.7.7")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.6.2")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.11.0")
